title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
copyedit: false
last_tested: "2026-01-23"
landing: true
steps:
  - title: Light a pixel
  - title: Make it random
    completion:
      - engaged
  - title: Add a loop
    completion:
      - external
  - title: "Challenge: better sparkles"
    challenge: true
