title: Sense HAT random sparkles
hero_image: images/banner.png
description: Create amazing random sparkles with your Sense HAT.
listed: true
copyedit: false
last_tested: "2026-01-23"
landing: true
steps:
  - title: Light a pixel
  - title: Make it random
    completion:
      - engaged
  - title: Add a loop
    completion:
      - external
  - title: "Challenge: better sparkles"
    challenge: true
